### ISSUE TITLE
could not be cloned error

### ISSUE THREAD

**Issue by ronag** [jasnell/piscina#130]
I'm a little confused as to what I'm doing wrong here?

```js
class Docs {
  constructor () {
    this.transferable = []
    this.value = []
  }

  push (msg) {
    const message = Buffer.from(msg)
    this.value.push({ message })
    this.transferable.push(message.buffer)
  }

  [transferableSymbol] () {
    return this.transferable
  }

  [valueSymbol] () {
    return this.value
  }
}

module.exports = async ({ keys }) => {
  const msgs = new Docs()
  return move(msgs)
}
```

```js
DataCloneError: [valueSymbol] () {
  return this.value
} could not be cloned.
```

**Comment by Prinzhorn** [comment]
Symbols cannot be cloned by the structured cloning algorithm that is used behind the scenes when using `postMessage` with the worker thread. Since you didn't provide a full example I assume you are trying to pass your custom class to or from a worker. That's not possible. Even without symbols in your object it would always end up as a plain Object on the other end without any prototype information.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm
https://nodejs.org/api/worker_threads.html#worker_threads_port_postmessage_value_transferlist

**Comment by ronag** [comment]
Ah, the symbols should be getters, not functions.
