### ISSUE TITLE
[ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"

### ISSUE THREAD

**Issue by Murena7** [jasnell/piscina#153]
Hi all, When I try to use .ts files with piscina I get an error. 
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"
Please explain how correctly use .ts files with the Piscina, thanks.

**Comment by jasnell** [comment]
Piscina runs on Node.js and uses Node.js module loading mechanisms. You'll need to transpile typescript files to JavaScript (either commonjs or ESM).

**Comment by Murena7** [comment]
> Piscina runs on Node.js and uses Node.js module loading mechanisms. You'll need to transpile typescript files to JavaScript (either commonjs or ESM).

Could you show some examples? How I can do this in the correct way? Because I tried a lot of solutions but none was worked

**Comment by danilomagalhaes** [comment]
@Murena7 you can use [ts-node](https://www.npmjs.com/package/ts-node), ts-node will JIT transpile any .ts imported files.

Eg: If I have one `event-loop-blocker-task.ts`

```typescript
export const run = (params: any): void => {
  // My event loop blocking code
};
```

I can create another file `ts-import.js` that imports my function and just 'bypass' any imported handler.

```javascript
require('ts-node').register({ transpileOnly: true });
const run = require('./event-loop-blocker-task');

module.exports = run;
```

You can also export multiple worker functions inside this file.

```javascript
require('ts-node').register({ transpileOnly: true });

const { function1, function2 } = require('./ts-workers');
const { run } = require('./event-loop-blocker-task');

module.exports = {
  function1,
  function2,
  run
}
```

Then you can just use the `ts-import.js` as Worker

```typescript
import Piscina = require('piscina');
import { resolve } from 'path';

const piscina = new Piscina({
  filename: resolve(__dirname, 'ts-import.js')
});

(async function() {
    piscina.run({ param: 'My Function 1 Param' }, { name: 'worker1' });
    piscina.run({ param: 'My Function 2 Param' }, { name: 'worker2' });
    piscina.run({ param: 'My Run Param' }, { name: 'run' });
})();
```

Be careful with the `transpileOnly: true` parameter passed to ts-node, without this parameter ts-node will take more time to transpile your code

**Comment by taxilian** [comment]
After a lot of experience using `ts-node` I've decided it's not worth the cost to use; it does make some things easier, but then when you deploy you have to send all of your typescript files and then startup time takes a lot longer; on one of my apps switching from shipping .ts files to transpiling during build and shipping just the `dist/` directory my startup time went from ~30 seconds to ~2 seconds, which is kindof a big deal IMO =] When using a worker I imagine it would be even more stark.

What I do is I use `source-map-support` so my stack traces are good and then I use `tsc-watch` to run the app; that transpiles to dist/ and runs my app, then restarts whenever.

If you use that method then making workers ends up being really easy:

```
const pdfWorker = new Piscina({
    filename: path.resolve(__dirname, 'pdf', 'index.js'),
});
```

The typescript file is `src/..../index.ts` but I know when it runs it will be `index.js`, so that's what I use.

FWIW =] Just found this project yesterday, I'm impressed so far.

**Comment by manju-reddys** [comment]
@taxilian Is it possible to share your folder structure (screen shot or ascii table) and tsconfig.json? I'm unable to get it working

**Comment by taxilian** [comment]
```
src/jobs/index.ts
src/jobs/pdf/index.ts
...
// builds to:
dist/jobs/index.js
dist/jobs/pdf/index.js
```

If it's not working then either you aren't transpiling and then running the JS or else you're making something way harder than it needs to be =] It's not very complicated. If you can provide some details on what isn't working I can try to help.

**Comment by manju-reddys** [comment]
I'm building a PDF generator, since the PDF will have 1000s of pages we convert the data (JSON) -> HTML -> PDF (Playwright / puppeteer), the data will be retrieved from proxy service, page by page in main thread -> compile to HTML in the separate thread -> generate PDF in separate thread, and once all pages are generated, will stitch them to a final PDF file.

This application is part of a monorepo (we use nx.dev) and everything written in TS, I attempted above 2 solutions but I couldn't get it working.

**Comment by taxilian** [comment]
@manju-reddys:  "It doesn't work" is about the most useless explanation of what is happening that you could possibly give. If you would like help then you need to provide details; as I said, I'd be happy to provide some insight, but with the details you've provided ("I tried it and it didn't work" there is no conceivable way anyone could assist.

With this or *any other request for aid you ever make* consider providing the following:

* Explain specifically what you tried, e.g. "I tried the method where I have typescript transpile to another directory and then executed the resulting javascript"
* Explain what happened when you tried that, e.g. "I got this message: <copy/paste message in a code block>", or "my computer spontaneously combusted", or "golang wouldn't compile my node.js code when I tried to do that" -- you'll note that all three options fit the level of detail which you have thus far provided.
* If there are troubleshooting steps you attempted which you expect are obvious things list those and the result

What you've done so far sounds far too much like "I don't have time to collect and explain everything I did that didn't work, so hey random stranger on the Internet who I don't know I'm sure you aren't busy so could you please just make a fully working example so that I can copy that instead?" -- I am willing to help, but I am *far* too busy to do your work for you =] I and others on the Internet are happy to help where we can, but if you want help you need to do your part to ask for it. =]

Good luck either way!

**Comment by perjerz** [comment]
#https://github.com/webpack/webpack.js.org/issues/4898#issuecomment-823073304
