### ISSUE TITLE
Any means to share memory from parent towards and among threads

### ISSUE THREAD

**Issue by jfoclpf** [jasnell/piscina#271]
I read all the documentation and I did not yet understand on how to share common memory amongst threads.

I know Node allows SharedArrayBuffer but I did not yet get how to implement it in Piscina
https://amagiacademy.com/blog/posts/2021-04-10/node-shared-array-buffer

I tried passing into `transferList` but I get an error

```js
const sharedUint8Array = new Uint8Array(new SharedArrayBuffer(4))
(async function () {
  const err = await piscina.run(
  { resDirectory, postalCode, cttData, openAddressesData, debug },
  {
    name: 'createCP4CP3jsonFile',
    transferList: [sharedUint8Array]
  })
})()
```

**Comment by metcoder95** [comment]
Hey!

What's the error you're facing?
This is the [list](https://nodejs.org/api/worker_threads.html#portpostmessagevalue-transferlist) of supported types that can be forwarded between Threads.

An `ArrayBuffer` cannot be shared through the TransferList as you can only share the buffer of the Array and render it on the other side, causing the `ArrayBuffer` to be unusable on the Main Thread.
If you want to share a `view` of a `SharedArrayBuffer` you need to use the [`Piscina.move`](https://github.com/piscinajs/piscina#static-method-movevalue) API to move Transfer the value to the desired Thread.

See the following [example](https://github.com/piscinajs/piscina/blob/current/examples/move/index.js).

See also the following [considerations](https://nodejs.org/api/worker_threads.html#considerations-when-transferring-typedarrays-and-buffers) if you're planning to maintain such kind of shares with your threads.

**Comment by jfoclpf** [comment]
Sorry, I code NodeJS for long time but I never had to deal with this low level instances, thus I am bit lost.

What I want is basically to have a normal JS Object created by the parent thread that is shared (read-only) amongst all children threads. I don't want to clone this JS Object, I want to share it because this JS Object is huge in terms of size in memory.

Can I achieve that? Can you show me an example?

**Comment by metcoder95** [comment]
Hmm, sadly don't think so. The issue here is how the data is being transferred from Parent -> Child threads. When passing any value as a message (not transfer list), those will be cloned using the Structured Clone algorithm, those includes Maps, Sets and plain JS Object. 

Even if you try to trick it like, e.g. using a combination of `JSON.stringify/parse` and `TextEncoder/TextDecoder`, you'll incur in serialization/deserialization costs when transferring and reconstructing the object on the Thread, meaning that you'll still need to re-create the huge JS Object on the thread.

Unless I'm missing something, sadly it is not entirely possible to not incur in such memory/cpu costs. One thing you can do is to either fetch the object within the Thread script or deconstruct it in smaller parts and share those parts into each Thread.

**Comment by jfoclpf** [comment]
Thank you @metcoder95 but unfortunately I need to whole object to be readable/shared by all children threads. Is there a way to use [`SharedArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) like they do [here](https://stackoverflow.com/questions/51053222/node-js-worker-threads-shared-object-store)?

**Comment by jfoclpf** [comment]
or perhaps [SharedWorker](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker)?

**Comment by metcoder95** [comment]
Sadly the concept of `SharedWorker` is not yet on Node.js. But one thing that you can do is something similar as the StackOverflow answer suggest. There you basically wrap every key/value over an index on the `SharedArrayBuffer`. Not sure how big is the object you want to share, but you’ll need to keep track of each index of the array for sure

**Comment by jfoclpf** [comment]
Thank you very much @metcoder95 for all your explanations
