### ISSUE TITLE
Version 3.3.0 on NPM

### ISSUE THREAD

**Issue by alolis** [jasnell/piscina#288]
Hello,

I was just wondering if there is going to be a v3.3.0 package release any time soon.

The reason I am asking is because I would like to use [this](https://github.com/piscinajs/piscina/pull/213) which it doesn't seem to exist in the v3.2.0 release at the moment.

Thank you for your time.

**Comment by dko-slapdash** [comment]
@jasnell @Elyahou Also super-interested in that "Add communication from worker to main thread" (https://github.com/piscinajs/piscina/pull/213) feature. It was merged back in May... and not released to NPM since that time.

BTW workerpool authors added a similar feature recently (but Piscina has a huge benefit of concurrentTasksPerWorker whilst workerpool does not, so Piscina is a preferred solution in many cases).

**Comment by metcoder95** [comment]
We'll be dropping v4 soon

**Comment by metcoder95** [comment]
v4 has been deployed recently 🙂
