### ISSUE TITLE
clarification: why use large maxQueue for optimal performance?

### ISSUE THREAD

**Issue by geertbrit** [jasnell/piscina#324]
In the docs it's mentioned to use a rather large queue (`maxThreads^2` as default) for optimal performance. 
I don't understand. Wouldn't a `queueSize = maxThreads`  (or rather: `queueSize = maxThreads * concurrentTasksPerWorker`) always be enough to keep all workers saturated?

**Comment by metcoder95** [comment]
It will if you assume you'll have the perfect scenario all the time where each workload takes exactly the same time to execute, plus you have constant traffic that is distributed equally across all threads.

Having the square of the `maxThreads` as the size of the queue attempts to keep **most of the threads** busy, and avoid idle situations where the thread just sits and waits for incoming work while consuming resources (zombie). Or even worst, killing it and having to start a new one once again, which adds the initial overhead.

Having such an amount is based on tests made within Piscina that showed that such a number kept the threads. But that doesn't mean that all the threads had the same amount of tasks all the time.

As always, depending on your workload and scenario, is better if you do your own benchmarks to see which combinations of settings (maybe starting from Piscina recommendations) fits better for your case 🙂

**Comment by geertbrit** [comment]
Thanks. I need to do some backpressure on the coordinator (bc of potential OOM situation lurking). 

This is due to first having to fan out over multiple threads and then combining them in the coordinator (so map-reduce effectively), but here a specific order of tasks is required. I.e.: if I processed jon 1 to 12 I have to wait for task 13 first. It's possible that tasks 14-100 are already done (or will be processed because they're queued) thus eating in on memory. 

Having a smaller queue gives me tighter bounds on this issue. 

Circling back for a sec if you don't mind.

> But that doesn't mean that all the threads had the same amount of tasks all the time.

Probably terribly naive, but I would expect a thread that's done to pick the first available task from the queue, which is still why I don't get on a technical level why a large queue is needed. Am I wrong, and are tasks in the queue already assigned to a particular thread somehow to speed things up? Perhaps a buffer to the child-process is already filled or something?

**Comment by metcoder95** [comment]
>This is due to first having to fan out over multiple threads and then combining them in the coordinator (so map-reduce effectively), but here a specific order of tasks is required. I.e.: if I processed jon 1 to 12 I have to wait for task 13 first. It's possible that tasks 14-100 are already done (or will be processed because they're queued) thus eating in on memory.
>
>Having a smaller queue gives me tighter bounds on this issue.

See what you mean, probably it will be worth it to try with a ring buffer for distributing the output from the threads?
Of course, will require initial coordination, but you can enqueue results and read from the ring as they're coming and as they're needing it. In that way, you can also automatically backpressure the thread pool in order to only consume as long as you need.

>Probably terribly naive, but I would expect a thread that's done to pick the first available task from the queue, which is still why I don't get on a technical level why a large queue is needed. Am I wrong, and are tasks in the queue already assigned to a particular thread somehow to speed things up? Perhaps a buffer to the child-process is already filled or something?

None of them, nor naive or wrong. Those are totally valid assumptions. The situation here is that Piscina spins up either the given `minThreads` or half of the total CPU count ([ref](https://github.com/piscinajs/piscina/blob/bcae345594fa5a6c306bff207fc95c14b021293a/src/index.ts#L140)).
Then, it will start distributing the incoming tasks among the threads with a FIFO algorithm. Then the thread receives work and is marked as busy. The algorithm will start looking for the threads that are not busy and give it the task. The order in how the tasks are finished depends totally on your situation. Once a thread finishes its task, it will sit and wait for being activated to do more work.
Piscina will distribute the tasks among the threads as long as the algorithm notices the first one is free.
