### ISSUE TITLE
Improvement: filename can be a module

### ISSUE THREAD

**Issue by jasnell** [jasnell/piscina#33]
/cc @addaleax

Because Piscina is using require/import to load the workers, it is actually possible for a worker to be a separate module. For example, given the following directory structure:

```
* node_modules
  * worker
    * index.js
    * package.json
* index.js
```

Where `/module_modules/worker/index.js` is the worker function,

From `/index.js` we can do the following and it just works...

```js
'use strict';

const Piscina = require('../..');
const { resolve } = require('path');

const piscina = new Piscina({ filename: resolve('./node_modules', 'worker') });

(async function () {
  const result = await piscina.runTask({ a: 4, b: 6 });
  console.log(result); // Prints 10
})();
```

While it's great that this works but the `resolve('./node_modules', ...` is a bit unfortunate. Just specifying `{ filename: 'worker' }` fails saying that the module `worker` cannot be found.

```console
james@ubuntu:~/nearform/piscina/examples/module$ node
Welcome to Node.js v14.1.0.
Type ".help" for more information.
> require('worker')
[Function (anonymous)]
> const Piscina = require('../..')
undefined
> const p = new Piscina({ filename: 'worker' })
undefined
> p.runTask().then(console.log)
Promise { <pending> }
> (node:23776) UnhandledPromiseRejectionWarning: Error: Cannot find module 'worker'
Require stack:
- /home/james/nearform/piscina/dist/src/worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /home/james/nearform/piscina/dist/src/worker.js:45:67
    at async getHandler (/home/james/nearform/piscina/dist/src/worker.js:45:19)
    at async /home/james/nearform/piscina/dist/src/worker.js:111:29
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Ideally `new Piscina({ filename: 'worker' })` would Just Work here.

That said, `filename` likely isn't the best name for the property here either :-)

**Comment by addaleax** [comment]
@jasnell The problem here is the same that we’d have with Worker threads in core if we wanted it to support there:

With `require` or `import`, the trick is that *every* module has its own instance of them, so that we can figure out where to start the resolution based on which module’s `require` or `import` started the module lookup.

With Workers, we cannot reasonably provide separate instances of the `Worker` constructor to individual modules, so that doesn’t work. And even if we did, that would be useless here, because the module that starts the `Worker`s is piscina, so that’s where the resolution algorithm would start (and not in the module that uses `piscina`).

Really the only thing Workers can do in this situation is to work based off the cwd, or to take absolute paths. In browsers, the situation is similar – I’m sure it would be desirable to be able to create Web Workers relative to the current module instead of the base URL, but that’s not technically feasible.

That’s also why the examples always resolve based off `__dirname` and not a relative path – anything else breaks once you run the application in a slightly different working directory.

**Comment by jasnell** [comment]
Oh yeah, definitely not trivial at all. I was considering playing around the idea of being able to pass the in scope require or import function as an option to Piscina but that's definitely a bit problematic also.

**Comment by addaleax** [comment]
@jasnell Yeah, I think that would work, at least once we have an equivalent of `require.resolve` in core for ESM.

But then the question is more or less, is passing `require.resolve(moduleName)` really easier than passing `require, moduleName` as two arguments?

**Comment by jasnell** [comment]
Ok, I'll experiment with this a bit to see if I can get something reasonable working for both commonjs and esm.

**Comment by jasnell** [comment]
Hmm... yeah, doesn't look like there's anything reasonable we can do here on the ESM front unless we can do something like `import.meta.import` that returns a reference to the `import()` function. Any changes here would need to be in core so I'm going to close this issue as inactionable for the time being.
