### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '...\app.asar\out\main\worker.js' imported from ...\app.asar\node_modules\piscina\dist\src\worker.js

### ISSUE THREAD

**Issue by archvlad** [jasnell/piscina#519]
Main process of Electron run fork.js via child_process.fork() method. fork.js is simple:
```javascript
const Piscina = require('piscina')
const path = require('path')

async function main() {
  const piscina = new Piscina({
    filename: path.resolve(__dirname, 'worker.js')
  })
  const result = await piscina.run({ name: 'Tom' })
  process.send({ result })
  console.log(result)
}

main()

```

Somehow this works in development but doesn't work in production. Also it's important to notice that I use `bytecodePlugin` from `electron-vite`

```javascript
main: {
    plugins: [externalizeDepsPlugin(), bytecodePlugin()],
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/main/index.js'),
          fork: resolve(__dirname, 'src/main/fork.js'),
          worker: resolve(__dirname, 'src/main/worker.js')
        }
      }
    }
  },
```

The error is:
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '...\app.asar\out\main\worker.js' imported from ...\app.asar\node_modules\piscina\dist\src\worker.js
Did you mean to import .../app.asar/out/main/worker.js?
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:326:11)
    at moduleResolve (node:internal/modules/esm/resolve:951:10)
    at defaultResolve (node:internal/modules/esm/resolve:1159:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1193:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:429:21) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.15.0

```

Here is the repository that reproduce error - https://github.com/archvlad/piscina-electron-issue

**Comment by metcoder95** [comment]
I gave it a try and the issue seems to be there, but sadly I'm not an Electron expert; what I can tell is that it seems that the resources needed by the app seems not be packed correctly, leading to a mismatch in the file-paths; maybe better to reach Electron's repo for some support

**Comment by tsekiguchi** [comment]
For anyone else that runs into this issue, I'd like to share the solution for posterity.

NB: This is for those using electron-vite. And while EV officially supports ESM, with the way that rollup works and packages the worker, it cannot read the worker. You must be using CJS in electron. Besides, the bytecode plugin only works with CJS too. 

In your main file, import the path to your worker (not the wrapper - no wrapper is needed because of rollup) by appending `*?modulePath` to the end of the path.
`import workerPath from './worker?modulePath';`

During compilation, rollup will now automatically create a separate file for the worker in your main folder output at the given path. We can now use this in Piscina.

Create a pool with Piscina, and use the imported path instead. For those using typescript, the filename export is not needed.
```
const pool = new Piscina({
  filename: workerPath,
  workerData: {
    userPath: path.join(app.getPath('userData'))
  }
})
```
For anyone accessing electron-specific modules inside their workers, you'll need to pass in those paths as workerData, as the electron api doesn't work inside of the workers. 

That's it! You can now use pool like normal in the Piscina docs.

For further help, reference the worker section of the docs from electron-vite. It's limited, but after lots of trial and error, I found the magic combination.

https://electron-vite.org/guide/dev#worker-threads

**Comment by metcoder95** [comment]
Amazing! Thanks for sharing, would you be willing to send a PR to add this to Piscina docs? It can be really helpful

**Comment by Dexus** [comment]
For the people who still have the problem: 

Using an example with electron-vite:

```

export default defineConfig({
  main: {
    resolve: {
      alias: {
        '@shared': resolve('src/shared/src')
      }
    },
    plugins: [externalizeDepsPlugin(), swcPlugin()],
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/main/index.ts'),
          worker_bg: resolve(__dirname, 'src/main/worker/background.worker.ts'), // your real worker
          worker: resolve(__dirname, 'node_modules/piscina/src/worker.ts') // the worker that comes with piscina
        }
      }
    }
  },
  // ....
}
```

So you can run it together with what in https://github.com/piscinajs/piscina/issues/519#issuecomment-2472081234 is mentioned!

**Comment by tsekiguchi** [comment]
Electron-vite is already pre-configured to handle workers, as I mentioned above. Instead of modifying your config file, let electron-vite do the work for you. 

```ts
import workerPath from './worker?modulePath';
```

Using workerPath in code with Piscina
```ts
const pool = new Piscina({
  filename: workerPath,
  // any additional options go here
})
```

Full detailed documentation from electron-vite here:
https://electron-vite.org/guide/dev#worker-threads

**Comment by Dexus** [comment]
I know this is the case, but I still get the error when compiling/packing that worker.js cannot be found, like the issue creator. Maybe an example would be helpful to see what I am doing wrong, especially because I create the code or the worker with Piscina "on the fly", because depending on the system settings, I still want to customize the Max Worker and co, which does not work afterwards to change.

**Comment by tsekiguchi** [comment]
Yes if you could share an example of your implementation, that would be helpful. 

In the config you provided, could you explain what you mean by 'worker that comes with Piscina"? You should be the one providing the worker, Piscina is just a framework for managing those workers.

Here's an example implementation based on your config

```ts
import backgroundWorkerPath from 'src/main/worker/background.worker?modulePath

const pool = new Piscina({
  filename: backgroundWorkerPath,
)}

await pool.run(dataPassedToWorker)
```

The original example is using a child_process.fork(), which spawns a new node process, then trying to run piscina inside of that fork. There shouldn't be a need to run a worker within a fork unless necessary, it's essentially a worker within a worker. The example repo isn't available anymore, but i'm assuming this is where the error occurred.

If you have further issues, check the output coming from vite. It should be generating a separate worker file.
